### ISSUE TITLE
GS_SLAS SE 29 05 not downloading

### ISSUE THREAD

**Issue by pepimanoli** [zhongjiedong/Tsukirim#115]
### What happened?

The file was updated recently and the old one is unavailable on Loverslab. This is not the same file that was reported missing on https://github.com/zhongjiedong/Tsukiro/issues/112#issuecomment-1145743984

### Modlist version

1.1.74

**Comment by pepimanoli** [comment]
Found the file on Patreon too:
https://www.patreon.com/posts/slal-29-05-67065507

**Comment by C0METTTT** [comment]
After downloading it from there did you have any problems? Becuase wabbajack wants me to go download it when it is in the folder, and if I try to skip it the installataion fails.

**Comment by zhongjiedong** [comment]
try again in one hour through the normal WJ app

**Comment by C0METTTT** [comment]
they updated it

**Comment by pepimanoli** [comment]
> After downloading it from there did you have any problems? Becuase wabbajack wants me to go download it when it is in the folder, and if I try to skip it the installataion fails.

It worked for me after downloading it from Patreon. Make sure you have the correct file, the one for SE.
