### ISSUE TITLE
Unable to download Arousal Based Breast Adjuster SE 5.4.2.7z 

### ISSUE THREAD

**Issue by Throwaway1203** [zhongjiedong/Tsukirim#175]
### What happened?

[FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Arousal Based Breast Adjuster SE 5.4.2.7z (ManualDownloader+State|https://www.loverslab.com/files/file/6671-arousal-based-breast-adjuster-for-se-abba/)

This got updated yesterday and the old file does exist in the form of the legacy download, but it doesn't get accepted by wabbajack. Figured it'd be worth reporting. I've tried redownloading the legacy version, unpacking it, repacking it into a .7z, and changing the name, but that doesn't seem to work. Not familiar with the internal machinations of Wabbajack so I can't take my troubleshooting much further.

### Modlist version

1.2.1

**Comment by zhongjiedong** [comment]
there is a temporary link here https://github.com/zhongjiedong/Tsukiro/blob/main/Arousal%20Based%20Breast%20Adjuster%20SE%205.4.2.7z
